- name: create HTML report
  template:
    src: report.j2
    dest: "{{ file_path }}/windows.html"

- name: copy CSS over
  copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true

- name: copy logo over
  copy:
    src: "webpage_logo.png"
    dest: "{{ file_path }}"
    directory_mode: true

- name: display link to inventory report
  debug:
    msg: "Please go to http://{{ansible_host}}/windows.html"