---
galaxy_info:
  author: Alex Dworjan
  description: Build Tags Report
  company: Red Hat, Inc.
  license: Apache License 2.0
  min_ansible_version: '2.9'
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
