---
- name: Create site directory structure
  ansible.windows.win_file:
    path: "{{ report_path }}"
    state: directory

- name: Get AD user accounts with groups and lock status
  ansible.windows.win_shell: |
    Import-Module ActiveDirectory
    Get-ADUser -Filter * -Property GivenName, Surname, SamAccountName, MemberOf, LockedOut |
    Select-Object GivenName, Surname, SamAccountName, @{Name="Groups";Expression={(Get-ADUser -Identity $_.SamAccountName -Property MemberOf |
    Select-Object -ExpandProperty MemberOf | Get-ADGroup | Select-Object -ExpandProperty Name) -join ", "}}, LockedOut |
    ConvertTo-Json
  register: ad_users

- name: Create HTML file from template
  ansible.windows.win_template:
    src: templates/users_template.html.j2
    dest: C:\Inetpub\wwwroot\user_info.html
  vars:
    users: "{{ ad_users.stdout | from_json }}"
