---
# - name: Set activation key for RHEL7
#   ansible.builtin.set_fact:
#     activation_key: RHEL7
#   when:
#     - ansible_distribution_version is match("7.*")
#     - shadowman_provision_hypervisor|default('RHV') != "Azure"
#     - shadowman_provision_hypervisor|default('RHV') != "AWS"

# - name: Set activation key for RHEL8
#   ansible.builtin.set_fact:
#     activation_key: RHEL8
#   when:
#     - ansible_distribution_version is match("8.*")
#     - shadowman_provision_hypervisor|default('RHV') != "Azure"
#     - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Set activation key for RHEL9
  ansible.builtin.set_fact:
    activation_key: RHEL9
  when:
    - ansible_distribution_version is match("9.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Set activation key for RHEL10
  ansible.builtin.set_fact:
    activation_key: RHEL10
  when:
    - ansible_distribution_version is match("10.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Generate registration command
  redhat.satellite.registration_command:
    smart_proxy: "capsule.shadowman.dev"
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    insecure: true
    setup_remote_execution: true
    ignore_subman_errors: true
    setup_insights: false
    validate_certs: false
    update_packages: false
    setup_remote_execution_pull: false
    activation_keys:
      - "{{ activation_key }}"
  become: false
  register: register_command
  delegate_to: localhost
  when:
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Perform registration
  ansible.builtin.shell:
    cmd: "{{ register_command.registration_command }}"
  register: register_result
  changed_when: "'The system has been registered with ID' in register_result.stdout"
  failed_when: "'Host was not found by the subscription UUID' in register_result.stdout"
  when:
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Use Activation Key to Register Azure RHEL Machine to RHSM
  community.general.redhat_subscription:
    state: present
    activationkey: "azure"
    org_id: "13247185"
  when: shadowman_provision_hypervisor | default('RHV') == "Azure"
  ignore_errors: true

# - name: Enable Repositories for RHEL 7
#   community.general.rhsm_repository:
#     name:
#       - rhel-7-server-rpms
#       - rhel-7-server-extras-rpms
#       - rhel-7-server-optional-rpms
#     purge: true
#   when:
#     - ansible_distribution_version is match("7.*")
#     - shadowman_provision_hypervisor|default('RHV') != "Azure"
#     - shadowman_provision_hypervisor|default('RHV') != "AWS"
#     - shadowman_provision_hypervisor|default('RHV') != "OCPV"

# - name: Enable Repositories for RHEL 8 when not using Azure base image
#   community.general.rhsm_repository:
#     name:
#       - rhel-8-for-x86_64-appstream-rpms
#       - rhel-8-for-x86_64-baseos-rpms
#     purge: true
#   when:
#     - ansible_distribution_version is match("8.*")
#     - shadowman_provision_hypervisor|default('RHV') != "Azure"
#     - shadowman_provision_hypervisor|default('RHV') != "AWS"
#     - shadowman_provision_hypervisor|default('RHV') != "OCPV"

- name: Enable Repositories for RHEL 9 when not using Azure base image
  community.general.rhsm_repository:
    name:
      - rhel-9-for-x86_64-appstream-rpms
      - rhel-9-for-x86_64-baseos-rpms
    purge: true
  when:
    - ansible_distribution_version is match("9.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"
    - shadowman_provision_hypervisor|default('RHV') != "OCPV"

- name: Enable Repositories for RHEL 10 when not using Azure base image
  community.general.rhsm_repository:
    name:
      - rhel-10-for-x86_64-appstream-rpms
      - rhel-10-for-x86_64-baseos-rpms
    purge: true
  when:
    - ansible_distribution_version is match("10.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"
    - shadowman_provision_hypervisor|default('RHV') != "OCPV"
