---
inactivity_timeout_value: !!str 900
var_password_pam_unix_remember: !!str 4
var_accounts_passwords_pam_faillock_deny: !!str 6
var_accounts_passwords_pam_faillock_unlock_time: !!str 1800
var_password_pam_dcredit: !!str -1
var_password_pam_lcredit: !!str -1
var_password_pam_minlen: !!str 7
var_password_pam_ucredit: !!str -1
var_password_hashing_algorithm: !!str SHA512
var_account_disable_post_pw_expiration: !!str 90
var_accounts_maximum_age_login_defs: !!str 90
var_auditd_action_mail_acct: !!str root
var_auditd_admin_space_left_action: !!str single
var_auditd_max_log_file: !!str 6
var_auditd_max_log_file_action: !!str rotate
var_auditd_num_logs: !!str 5
var_auditd_space_left_action: !!str email
var_multiple_time_servers: !!str 0.rhel.pool.ntp.org,1.rhel.pool.ntp.org,2.rhel.pool.ntp.org,3.rhel.pool.ntp.org
sshd_idle_timeout_value: !!str 900